apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generic-device-plugin
- descheduler/ks.yaml
- intel-device-plugin/ks.yaml
- node-feature-discovery/ks.yaml
- reloader/ks.yaml
- kube-web-view
- git-sync-reloader-adapter
