---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rtlamr-device
spec:
  rules:
    - name: rtlamr
      labels:
        rtlamr.feature.node.kubernetes.io/rtlamr: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: "0bda" }
            device: { op: In, value: "2838" }
