---
# yaml-language-server: $schema=https://schemas.hydaz.com/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-immich
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://cloudnative-pg-immich/
    endpointURL: https://s3.internal.${SECRET_DOMAIN}
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-immich-secret
        key: aws-access-key-id
      secretAccessKey:
        name: cloudnative-pg-immich-secret
        key: aws-secret-access-key
    wal:
      compression: bzip2
      maxParallel: 8
    data:
      compression: bzip2
