---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password-connect.yaml
  - intel.yaml
  - node-feature-discovery.yaml
  - backube.yaml
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - grafana.yaml
  - jetstack.yaml
  - openebs.yaml
  - piraeus.yaml
  - prometheus-community.yaml
  - rook-ceph.yaml
  - stakater.yaml
