---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smtp-relay
spec:
  secretName: tls.smtp-relay
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: smtp.internal.${SECRET_DOMAIN}
  dnsNames:
    - smtp.internal.${SECRET_DOMAIN}
  privateKey:
    rotationPolicy: Always
