apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: actual-budget-internal
spec:
  hostnames:
    - "actual.internal.${SECRET_DOMAIN}"
    - "ab.internal.${SECRET_DOMAIN}"
  parentRefs:
    - name: internal
      namespace: network
  rules:
    - backendRefs:
        - kind: Service
          name: actual-budget
          port: 80
