---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        DB_HOSTNAME: &dbhost immich-rw.database.svc.cluster.local
        DB_USERNAME: &dbuser "{{ .IMMICH_DB_USERNAME }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_DB_PASSWORD }}"
        DB_DATABASE_NAME: &dbname immich
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: "dummyuser" # we don't use this but it's required
        INIT_POSTGRES_PASS: "{{ .IMMICH_DUMMY_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: *dbuser
        INIT_POSTGRES_SUPER_PASS: *dbpass
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-config-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "backup": {
              "database": {
                "cronExpression": "0 02 * * *",
                "enabled": true,
                "keepLastAmount": 14
              }
            },
            "logging": {
              "enabled": true,
              "level": "log"
            },
            "newVersionCheck": {
              "enabled": true
            },
            "notifications": {
              "smtp": {
                "enabled": false,
                "from": "",
                "replyTo": "",
                "transport": {
                  "host": "",
                  "ignoreCert": false,
                  "password": "",
                  "port": 587,
                  "secure": false,
                  "username": ""
                }
              }
            },
            "oauth": {
              "enabled": true,
              "autoRegister": true,
              "clientId": "immich",
              "clientSecret": "{{ .OAUTH_CLIENT_SECRET }}",
              "issuerUrl": "https://auth.internal.${SECRET_DOMAIN}"
            },
            "passwordLogin": {
              "enabled": false
            },
            "server": {
              "externalDomain": "https://photos.internal.${SECRET_DOMAIN}"
            },
            "trash": {
              "days": 30,
              "enabled": true
            },
            "user": {
              "deleteDelay": 7
            }
          }
  data:
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: authelia
        property: IMMICH_OAUTH_CLIENT_SECRET
