---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        # Mosquitto
        FRIGATE_MQTT_USERNAME: "{{ .MQTT_FRIGATE_USER }}"
        FRIGATE_MQTT_PASSWORD: "{{ .MQTT_FRIGATE_PASSWORD }}"

        # Frigate Auth
        PLUS_API_KEY: "{{ .FRIGATE_PLUS_API_KEY }}"

        # camera auth
        FRIGATE_CAMERA_USER: "{{ .FRIGATE_CAMERA_USER }}"
        FRIGATE_CAMERA_PASSWORD: "{{ .FRIGATE_CAMERA_PASSWORD }}"

        # ip addresses
        FRIGATE_DOORBELL_IP: "{{ .FRIGATE_DOORBELL_IP }}"
        FRIGATE_DRIVEWAY_IP: "{{ .FRIGATE_DRIVEWAY_IP }}"
        FRIGATE_BAY_WINDOW_IP: "{{ .FRIGATE_BAY_WINDOW_IP }}"
        FRIGATE_MOUNTAIN_SIDE_IP: "{{ .FRIGATE_MOUNTAIN_SIDE_IP }}"

  dataFrom:
    - extract:
        key: frigate
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MQTT_$1"
