apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lldap-internal
spec:
  hostnames:
    - "ldap.internal.${SECRET_DOMAIN}"
    - "lldap.internal.${SECRET_DOMAIN}"
  parentRefs:
    - name: internal
      namespace: network
  rules:
    - backendRefs:
        - kind: Service
          name: lldap
          port: 80
